TempMotoWeb/Controllers/MedicaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TempMotoWeb.Data;
using TempMotoWeb.Models;

namespace TempMotoWeb.Controllers
{
    public class MedicaoController : Controller
    {
        private readonly TempMotoWebContext _context;

        public MedicaoController(TempMotoWebContext context)
        {
            _context = context;
        }

        // GET: Medicao
        public async Task<IActionResult> Index()
        {
              return _context.Medicao != null ? 
                          View(await _context.Medicao.ToListAsync()) :
                          Problem("Entity set 'TempMotoWebContext.Medicao'  is null.");
        }

        // GET: Medicao/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Medicao == null)
            {
                return NotFound();
            }

            var medicao = await _context.Medicao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicao == null)
            {
                return NotFound();
            }

            return View(medicao);
        }

        // GET: Medicao/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicao/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Latitude,Longitude,Altitude,Temperatura,Umidade,Num_Satelites,Velocidade,Data_Medicao")] Medicao medicao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicao);
        }

        // GET: Medicao/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Medicao == null)
            {
                return NotFound();
            }

            var medicao = await _context.Medicao.FindAsync(id);
            if (medicao == null)
            {
                return NotFound();
            }
            return View(medicao);
        }

        // POST: Medicao/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Latitude,Longitude,Altitude,Temperatura,Umidade,Num_Satelites,Velocidade,Data_Medicao")] Medicao medicao)
        {
            if (id != medicao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicaoExists(medicao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicao);
        }

        // GET: Medicao/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Medicao == null)
            {
                return NotFound();
            }

            var medicao = await _context.Medicao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicao == null)
            {
                return NotFound();
            }

            return View(medicao);
        }

        // POST: Medicao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Medicao == null)
            {
                return Problem("Entity set 'TempMotoWebContext.Medicao'  is null.");
            }
            var medicao = await _context.Medicao.FindAsync(id);
            if (medicao != null)
            {
                _context.Medicao.Remove(medicao);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicaoExists(int id)
        {
          return (_context.Medicao?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> Mapa()
        {
            return View(await _context.Medicao.ToListAsync());
        }
        public async Task<IActionResult> Grafico()
        {
            return View(await _context.Medicao.ToListAsync());
        }
    }
}

TempMotoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TempMotoWeb</title>
    <script>
        const baseUrl = "@Environment.GetEnvironmentVariable("baseUrl")";
        const mapsKey = "@Environment.GetEnvironmentVariable("mapsKey")";
    </script>
    @RenderSection("Header", required:false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TempMotoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Medicao" asp-action="Index">TempMotoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicao" asp-action="Index">Lista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicao" asp-action="Mapa">Mapa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicao" asp-action="Grafico">Grafico</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TempMotoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>